### ISSUE TITLE
Migrate to JUnit5

### ISSUE THREAD

**Issue by brbog** [rzo1/crawler4j#113]
Current Maven surefire plugin should have support for JUnit5 tests, so I think getting rid of older JUnit dependencies (and updating some existing tests) could do the trick.

Verify that it works by deliberately introducing failures inside:
edu.uci.ics.crawler4j.tests.parser.CssParseDataTest.nonParsableCssHaltingOnErrorTrueTest()
edu.uci.ics.crawler4j.tests.parser.CssParseDataTest.nonParsableCssHaltingOnErrorFalseTest()

**Comment by rzo1** [comment]
`3.0.0-M6` should work fine. Might be an issue with the groovy things, but we can get of them anyway.

**Comment by brbog** [comment]
@rzo1 : I took a stab at it and noticed that groovy-all had a dependency on groovy-test, which had a dependency on JUnit4. After removing this, I had to work on the Spock tests.

I'm seeing:
- Spock tests that shouldn't even compile after the introduction of FrontierConfiguration
- the PageTest contains `ContentType.create("text/html", "UNPARSABLE"),`, which throws an error if you try to execute this code

=> I doubt that these tests are still being executed by the build.

I was able to migrate a couple of Spock tests that are using WireMock to JUnit5, so I'll try to go through all of them. That will also allow to clean up the Maven configuration afterwards (get rid of anything related to Groovy).

This is a bit of a "first step" to allow more people to contribute (not everybody knows Spock and/or Groovy), but it will be a commit that is rather big and probably not really reviewable, just so you know :-). Not sure if you want to make a tag or a release beforehand or if we just go for it and want a version 5 with everything Spock/Groovy related removed?

I'm keeping the code/configuration changes as minimal as possible so they can be reviewed in later commits.

**Comment by rzo1** [comment]
> This is a bit of a "first step" to allow more people to contribute (not everybody knows Spock and/or Groovy), but it will be a commit that is rather big and probably not really reviewable, just so you know :-). Not sure if you want to make a tag or a release beforehand or if we just go for it and want a version 5 with everything Spock/Groovy related removed?

How we write tests shouldn't influence the way the framework works, no? ;) So I am fine with a hard switch and purge Spock/Groovy in v5.

**Comment by rzo1** [comment]
@brbog is this completed?

**Comment by brbog** [comment]
Jup, closing.
