### ISSUE TITLE
Support dependency for Gradle

### ISSUE THREAD

**Issue by SinonCute** [rzo1/crawler4j#151]

**Comment by rzo1** [comment]
The framework / sdk is available on Maven Central. Therefore, it should be available via Gradle too. Can you elaborate, what issue you are facing exactly?

**Comment by SinonCute** [comment]
I don't know exactly how to add implement to Gradle.

**Comment by SinonCute** [comment]
any I have specific question is with crawler can I get data on networking tab?

**Comment by rzo1** [comment]
> I don't know exactly how to add implement to Gradle.

https://docs.gradle.org/current/userguide/dependency_management_for_java_projects.html

something like

```json
plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'de.hs-heilbronn.mi:crawler4j-with-hsqldb:5.0.0'
}
````

**Comment by rzo1** [comment]
> and I have specific question is with crawler can I get data on networking tab?

Better use Stackoverflow or Discussions for these kind of questions
