### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by brbog** [rzo1/crawler4j#73]
Thanks for the evolution of this nice framework (I guess the frontiers part + using Maven are your vision?). I hope this helps as well.

I submitted a pull request with only documentation updates regarding adding extra urls to crawl and guarding against crawling certain urls.

**Comment by rzo1** [comment]
Hi! Thanks for the PR - I will look into it as soon as my ISP provides me with Internet again ;-)

Yes - we wanted to get rid of Gradle as well as Sleepycat - so we thought it would be nice to abstract the frontier impl a bit ;)

**Comment by brbog** [comment]
Good stuff :-), motivated me to contribute a little bit!
