### ISSUE TITLE
bug: incorrect extraction of absolute urls from css

### ISSUE THREAD

**Issue by brbog** [rzo1/crawler4j#80]
This is a more tricky one. A pull request containing tests for absolute and relative urls is coming.

It's possible that following code inside the CssParseData.getLinkRelativeTo()-method should be altered:
```java
        if (linkUrl.startsWith("http")) {
            return getPathFromUrl(linkUrl);
        }
```
to just return the `linkUrl`, but it's a rather invasive change, so better verify.

Since the css parsing can't be substituted, a workaround is to create a custom Parser and override the parse()-method.

**Comment by rzo1** [comment]
Yes - I think you are right. Doesn't make much sense to assume, that a http reference in css always links to the referring page's hostname.

**Comment by brbog** [comment]
I put a fix that also removes a bunch of code in the PR -> see comment on PR as well. Replying here in case anyone reads this thread and is wondering what happened next. I'm still discovering what the ideal conversation flow is in GitHub :-).
